name: Deploy to Production

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and deploy with Docker Compose
        run: |
          docker compose build --no-cache
          docker compose down
          docker compose  up -d
